# -*- coding: utf-8 -*-
"""Fetch SRE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DqjXKNF2F4r4n7ft21yRAkbXGE4BHlV
"""

import yaml
import requests
import time
# import ipdb
from collections import defaultdict

# Function to load configuration from the YAML file
def load_config(file_path):
    # ipdb.set_trace()
    with open(file_path, 'r') as file:
        return yaml.safe_load(file)

# Function to perform health checks
def check_health(endpoint):
    # ipdb.set_trace()
    url = endpoint['url']
    method = endpoint.get('method', 'HEAD')
    headers = endpoint.get('headers')
    body = endpoint.get('body', None)

    try:
        begin = time.time()
        response = requests.request(method, url, headers=headers, data=body)
        end = time.time()
        response_time = ( end - begin ) * 1000
        print(f"{url} took {response_time} seconds")
        print(f"{response.elapsed.total_seconds() * 1000}")

        if 200 <= response.status_code < 300 and response_time <= 500:
            return "UP"
        else:
            return "DOWN"
    except requests.RequestException:
        return "DOWN"

# Main function to monitor endpoints
def monitor_endpoints(file_path):
    # ipdb.set_trace()
    config = load_config(file_path)
    domain_stats = defaultdict(lambda: {"up": 0, "total": 0})

    while True:
        for endpoint in config:
            domain = endpoint["url"].split("//")[-1].split("/")[0]
            result = check_health(endpoint)

            domain_stats[domain]["total"] += 1
            if result == "UP":
                domain_stats[domain]["up"] += 1

        # Log cumulative availability percentages
        for domain, stats in domain_stats.items():
            availability = round(100 * stats["up"] / stats["total"])
            print(f"{domain} has {availability}% availability percentage")

        print("---")
        time.sleep(15)

# Entry point of the program
if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        print("Usage: python monitor.py <config_file_path>")
        sys.exit(1)

    # config_file = sys.argv[1]
    config_file = 'sample.yaml'
    try:
        monitor_endpoints(config_file)
    except KeyboardInterrupt:
        print("\nMonitoring stopped by user.")

# !pip install ipdb